### ISSUE TITLE
#5 Opções de Pagamento

### ISSUE THREAD

**Issue by rodrigolmacedo** [otavioprado/fiap-tech-challenge-parquimetro#4]
- [x] Os condutores têm a opção de pagar pelo estacionamento de várias maneiras, incluindo cartão de crédito,
débito ou PIX, dependendo da forma de pagamento registrada.

- [x] A cobrança é baseada no tempo utilizado; para tempos fixos, o valor total é cobrado independentemente do
tempo real utilizado, enquanto para períodos variáveis, a cobrança é por hora completa.

**Comment by ghost** [comment]
feito
